[tox]
minversion = 3.21
# relies on the correct version of Python installed
envlist = ruff,tests,mypy,ty
# https://github.com/tox-dev/tox/issues/20#issuecomment-247788333
# hack to prevent .tox from crapping to the project directory
toxworkdir = {env:TOXWORKDIR_BASE:}{toxinidir}/.tox

[testenv]
# TODO how to get package name from setuptools?
package_name = orgparse
pass_env =
    # useful for tests to know they are running under ci
    CI
    CI_*
    # respect user's cache dirs to prevent tox from crapping into project dir
    PYTHONPYCACHEPREFIX
    MYPY_CACHE_DIR
    RUFF_CACHE_DIR

set_env =
    # do not add current working directory to pythonpath
    # generally this is more robust and safer, prevents weird issues later on
    PYTHONSAFEPATH=1


[testenv:clean]
skip_install = true
deps =
allowlist_externals = rm
commands =
    rm -rf .coverage .coverage.* htmlcov .mypy-report .pytest_cache .tox/dist
    {envpython} -c "import pathlib; [p.unlink() for p in pathlib.Path('.').rglob('*.pyc')]; [p.rmdir() for p in pathlib.Path('.').rglob('__pycache__')]"


[testenv:ruff]
skip_install = true
deps =
    ruff
commands =
    {envpython} -m ruff check src tests {posargs}


[testenv:tests]
deps =
    pytest
    pytest-cov
commands =
    # Run tests from the tests/ directory
    # posargs allow test filtering, e.g. tox -e tests -- -k test_name
    {envpython} -m pytest \
        tests/ \
        --cov={[testenv]package_name} \
        --cov-report=term-missing \
        --cov-report=html:htmlcov \
        {posargs}


[testenv:mypy]
deps =
    mypy
    pytest  # needed if you have test files with type hints
commands =
    {envpython} -m mypy \
        --install-types \
        --non-interactive \
        src/{[testenv]package_name} \
        --txt-report .mypy-report \
        --html-report .mypy-report \
        --cobertura-xml-report .mypy-report \
        {posargs}


[testenv:ty]
extras = optional
deps =
    pytest
    typeguard
commands =
    {envpython} -m pytest \
        tests/ \
        --typeguard-packages={[testenv]package_name} \
        {posargs}
